version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      # circleci/python:3 is based on debian:buster where we don't have gmsh 4.4.1 yet
      # - image: circleci/python:3
      - image: ubuntu:19.10
    steps:
      - run: apt update
      - run: apt install -y gmsh python3-pip
      - run: pip3 install excode tox
      - checkout
      # The actual test
      - run: excode README.md test/readme_test.py --filter python,test
      - run: tox
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
