{% set version = "6.0.5" %}

package:
    name: pygmsh
    version: {{ version }}

source:
    path: ../

build:
    number: 0

requirements:
    host:
        - python >=3.6
        - setuptools
        - numpy >=1.9
        - meshio >=4.0

    run:
        - python
        - meshio >=4.0
        - numpy >=1.9

test:
    source_files:
        - test
    requires:
        - pytest
    commands:
        - pytest

about:
    home: https://github.com/nschloe/pygmsh
    license: MIT
    summary: Gmsh for Python.
    description: pygmsh provides a python interface for the Gmsh scripting language.
    dev_url: https://github.com/nschloe/pygmsh
    doc_url: https://pypi.org/project/pygmsh/
    doc_source_url: https://github.com/nschloe/pygmsh/blob/master/README.md
